language: node_js

env:
     - DATABASE_URL=postgresql://postgres@localhost:5432/greet_db

node_js:
  - "v8.9.4"

before_script:
  - psql -c 'create database  greet_db;' -U postgres
  - psql -U postgres -d greet_db -a -f database.sql
  
addons:
    apt:
    packages:
    - postgresql-server-dev-9.2