language: node_js
node_js:
  - "v8.9.4"

before_script:
  - psql -c 'create database  greet_db;' -U postgres
  - psql -c 'create table hold_name(id serial not null primary key, names text not null, counter int not null);' -U postgres

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2