language: node_js
node_js:
  - "v8.9.4"
# before_script:
#   - psql -c "CREATE DATABASE hold_name;" -U postgres
#   - psql -c "CREATE TABLE hold_name(id serial not null primary key, names text not null, counter int not null);" -U postgres
  before_script:
  - psql -c 'create database  hold_name;' -U postgres
  - psql -U postgres -d hold_name -a -f database.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2